syntax = "proto2";
package openapi;
message ProtoMessage {
 required uint32 payloadType = 1;
 optional bytes payload = 2;
 optional string clientMsgId = 3;
}
enum ProtoPayloadType {
 PROTO_MESSAGE = 5;
 ERROR_RES = 50;
 HEARTBEAT_EVENT = 51;
 OA_APPLICATION_AUTH_REQ = 2100;
 OA_APPLICATION_AUTH_RES = 2101;
 OA_ACCOUNT_AUTH_REQ = 2102;
 OA_ACCOUNT_AUTH_RES = 2103;
 OA_SYMBOLS_LIST_REQ = 2114;
 OA_SYMBOLS_LIST_RES = 2115;
 OA_TRADER_REQ = 2121;
 OA_TRADER_RES = 2122;
 OA_RECONCILE_REQ = 2124;
 OA_RECONCILE_RES = 2125;
}
