import { createClient } from '@base44/sdk';

export interface Base44SignalEvaluationRequest {
  pair: string;
  timeframe: string;
  direction: 'BUY' | 'SELL';
  currentPrice: number;
  entryPrice: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2?: number;
  riskRewardRatio?: string;
  confidence: number;
  reasons: string[];
  indicators?: {
    rsi?: number;
    macd?: { histogram?: number };
    adx?: { adx?: number; plusDI?: number; minusDI?: number };
    superTrend?: { trend?: string };
  };
  smc?: {
    orderBlocksCount?: number;
    fvgCount?: number;
    lastStructureBreak?: string;
  };
}

export interface Base44SignalEvaluationResult {
  decision: 'CONFIRM' | 'VETO' | 'ADJUST';
  confidenceScore: number;
  adjustedEntry?: number;
  adjustedSL?: number;
  adjustedTP?: number;
  reasoning: string;
  riskWarning?: string;
  provider: 'base44' | 'gemini_fallback' | 'local_fallback';
  cached?: boolean;
}

export interface Base44WeeklyReviewRequest {
  totalClosed: number;
  winsCount: number;
  lossesCount: number;
  winRate: number;
  netPnL: number;
  sampleClosedTrades?: any[];
}

export interface Base44WeeklyReviewResult {
  success: boolean;
  timestamp: number;
  tradesReviewedCount: number;
  winCount: number;
  lossCount: number;
  winRate: number;
  netPnLDollars: number;
  executiveSummaryMs: string;
  keyMistakesMs: string[];
  winningPatternsMs: string[];
  generatedAdaptiveRulesMs: string[];
  setupTuningRecommendationsMs: string[];
  primaryActiveRule: string;
  provider: 'base44' | 'gemini_fallback' | 'local_fallback';
  tokensUsedEstimate: number;
}

export class Base44AiService {
  private static instance: Base44AiService;
  private client: any = null;
  private isConfigured: boolean = false;
  private evaluationCache: Map<string, { result: Base44SignalEvaluationResult; timestamp: number }> = new Map();
  private readonly CACHE_TTL_MS = 15 * 60 * 1000; // 15 mins cache to strictly save tokens

  private constructor() {
    this.initClient();
  }

  public static getInstance(): Base44AiService {
    if (!Base44AiService.instance) {
      Base44AiService.instance = new Base44AiService();
    }
    return Base44AiService.instance;
  }

  private initClient(): void {
    const token = process.env.BASE44_ACCESS_TOKEN?.trim();
    const appId = process.env.BASE44_APP_ID?.trim() || '6a3f271e41dc4ee0d0d5abdf';

    if (token && appId) {
      try {
        this.client = createClient({ appId });
        this.client.setToken(token);
        this.isConfigured = true;
        console.log(`[Base44AiService] Initialized with App ID: ${appId} (Personal Access Token active)`);
      } catch (err: any) {
        console.warn(`[Base44AiService] Failed to initialize client: ${err.message}`);
        this.isConfigured = false;
      }
    } else {
      this.isConfigured = false;
    }
  }

  public isAvailable(): boolean {
    return this.isConfigured && this.client !== null;
  }

  /**
   * Generates a cache key to prevent duplicate LLM calls on identical market states.
   */
  private getCacheKey(req: Base44SignalEvaluationRequest): string {
    const priceBucket = Math.round(req.currentPrice * 1000);
    return `${req.pair.replace(/[^A-Za-z0-9]/g, '').toUpperCase()}_${req.direction}_${req.timeframe}_${priceBucket}`;
  }

  /**
   * Evaluates a trade candidate generated by the algorithmic scanner.
   * Strictly enforces token-saving rules:
   * 1. 15-minute deduplication cache
   * 2. Quality filter (low confidence / poor R:R rejected locally with 0 tokens spent)
   * 3. Compact high-density prompt with JSON Schema enforcement
   */
  public async evaluateTradeSignal(
    req: Base44SignalEvaluationRequest
  ): Promise<Base44SignalEvaluationResult> {
    // 1. Cache Check: Save tokens if this setup was already analyzed recently
    const cacheKey = this.getCacheKey(req);
    const cached = this.evaluationCache.get(cacheKey);
    if (cached && (Date.now() - cached.timestamp < this.CACHE_TTL_MS)) {
      console.log(`[Base44AiService] Token Saved: Returning cached evaluation for ${req.pair} (${req.direction}).`);
      return { ...cached.result, cached: true };
    }

    // 2. Pre-filter: Reject mathematically weak signals before calling LLM
    // Threshold: 64% — below this, even an ADJUST cannot produce a safe trade
    if (req.confidence < 64) {
      const localReject: Base44SignalEvaluationResult = {
        decision: 'VETO',
        confidenceScore: req.confidence,
        reasoning: 'Algorithmic confidence below minimum threshold (<64%). Discarded locally to save AI tokens.',
        provider: 'local_fallback'
      };
      return localReject;
    }

    if (!this.isAvailable()) {
      return this.fallbackLocalEvaluation(req, 'Base44 credentials not configured');
    }

    try {
      // 3. Compact High-Density Prompt (Minimizes input tokens)
      const compactPrompt = [
        `You are Senior Desk Chief Risk Controller for Quantum AI.`,
        `Evaluate this Grade-A trade setup and provide a strict second opinion:`,
        `Asset: ${req.pair} | Dir: ${req.direction} | TF: ${req.timeframe}`,
        `Spot: ${req.currentPrice} | Entry: ${req.entryPrice} | SL: ${req.stopLoss} | TP1: ${req.takeProfit1}`,
        `Algorithmic Confidence: ${req.confidence}% | R:R: ${req.riskRewardRatio || '1:2.0'}`,
        `Technical Confluences:`,
        `- RSI: ${req.indicators?.rsi ?? 'N/A'} | ADX: ${req.indicators?.adx?.adx ?? 'N/A'}`,
        `- SuperTrend: ${req.indicators?.superTrend?.trend ?? 'N/A'}`,
        `- SMC: ${req.smc?.orderBlocksCount || 0} OBs, ${req.smc?.fvgCount || 0} FVGs, Structure: ${req.smc?.lastStructureBreak || 'Normal'}`,
        `- Key Reasons: ${(req.reasons || []).slice(0, 3).join(', ')}`,
        `Decision Protocol:`,
        `- CONFIRM: Setup is technically robust with clear edge. No level changes needed.`,
        `- VETO: Setup is trapped, counter-trend, or genuinely high risk. Only use if direction is wrong or trap is present.`,
        `- ADJUST: Direction is valid BUT levels need improvement. MANDATORY: you MUST provide specific numeric adjustedSL and adjustedTP values in your response.`,
        `IMPORTANT: Prefer ADJUST over VETO whenever the trade direction is valid but risk parameters need improvement.`,
        `When you return ADJUST, you MUST fill adjustedSL and adjustedTP with safer values. Do NOT return ADJUST without level values.`,
        `Respond strictly matching the JSON schema.`
      ].join('\n');

      const response = await this.client.integrations.Core.InvokeLLM({
        prompt: compactPrompt,
        response_json_schema: {
          type: 'object',
          properties: {
            decision: { type: 'string', enum: ['CONFIRM', 'VETO', 'ADJUST'] },
            confidenceScore: { type: 'number', minimum: 0, maximum: 100 },
            adjustedEntry: { type: 'number' },
            adjustedSL: { type: 'number' },
            adjustedTP: { type: 'number' },
            reasoning: { type: 'string' },
            riskWarning: { type: 'string' }
          },
          required: ['decision', 'confidenceScore', 'reasoning']
        }
      });

      const parsed: Base44SignalEvaluationResult = {
        decision: response.decision || 'CONFIRM',
        confidenceScore: Number(response.confidenceScore) || req.confidence,
        adjustedEntry: response.adjustedEntry ? Number(response.adjustedEntry) : undefined,
        adjustedSL: response.adjustedSL ? Number(response.adjustedSL) : undefined,
        adjustedTP: response.adjustedTP ? Number(response.adjustedTP) : undefined,
        reasoning: response.reasoning || 'Evaluated and approved by Base44 Intelligence.',
        riskWarning: response.riskWarning || undefined,
        provider: 'base44'
      };

      // Store in 15-minute token-saver cache
      this.evaluationCache.set(cacheKey, { result: parsed, timestamp: Date.now() });

      console.log(`[Base44AiService] Dispatched Second Opinion for ${req.pair} ${req.direction} -> ${parsed.decision} (${parsed.confidenceScore}%)`);
      return parsed;
    } catch (err: any) {
      console.warn(`[Base44AiService] InvokeLLM error: ${err.message}. Falling back.`);
      return this.fallbackLocalEvaluation(req, err.message);
    }
  }

  private fallbackLocalEvaluation(req: Base44SignalEvaluationRequest, reason: string): Base44SignalEvaluationResult {
    return {
      decision: req.confidence >= 64 ? 'CONFIRM' : 'VETO',
      confidenceScore: req.confidence,
      reasoning: `Base44 fallback: ${reason}. Approved by local quantitative SMC rule engine.`,
      provider: 'local_fallback'
    };
  }

  /**
   * Evaluates economic news release outcome bias.
   */
  public async evaluateNewsOutcome(params: {
    title: string;
    currency: string;
    actual: string;
    forecast: string;
    previous: string;
  }): Promise<{ directionalBias: 'BULLISH' | 'BEARISH' | 'NEUTRAL'; strength: number; summary: string }> {
    if (!this.isAvailable()) {
      return { directionalBias: 'NEUTRAL', strength: 50, summary: 'Local analysis default.' };
    }

    try {
      const res = await this.client.integrations.Core.InvokeLLM({
        prompt: `Analyze economic news release: Event: ${params.title} (${params.currency}), Actual: ${params.actual}, Forecast: ${params.forecast}, Previous: ${params.previous}. Determine directional bias for ${params.currency} and give strength 1-100.`,
        response_json_schema: {
          type: 'object',
          properties: {
            directionalBias: { type: 'string', enum: ['BULLISH', 'BEARISH', 'NEUTRAL'] },
            strength: { type: 'number', minimum: 1, maximum: 100 },
            summary: { type: 'string' }
          },
          required: ['directionalBias', 'strength', 'summary']
        }
      });

      return {
        directionalBias: res.directionalBias || 'NEUTRAL',
        strength: Number(res.strength) || 75,
        summary: res.summary || `${params.currency} outcome evaluated by Base44.`
      };
    } catch (err: any) {
      console.warn(`[Base44AiService] News evaluation error: ${err.message}`);
      return { directionalBias: 'NEUTRAL', strength: 50, summary: 'Local fallback evaluation.' };
    }
  }

  /**
   * Conducts Weekly Performance & Adaptive Setup Tuning Review using Base44 InvokeLLM.
   * Runs at low frequency (once weekly) with a compact prompt to strictly conserve monthly token budget.
   * Estimated token usage: ~350 - 400 tokens per weekly review.
   */
  public async runWeeklyHomeworkReview(
    req: Base44WeeklyReviewRequest
  ): Promise<Base44WeeklyReviewResult> {
    const defaultMistakes = [
      "Entri terburu-buru sebelum pengesahan Liquidity Grab / Sweep 15M.",
      "Penetapan Stop Loss terlalu ketat tanpa mengambil kira julat volatiliti ATR 1.5x.",
      "Membuka posisi sewaktu tetingkap berita berimpak tinggi tanpa perlindungan buffer."
    ];
    const defaultWinning = [
      "Rejection bersih pada Zon Order Block (OB) sejajar arah trend utama.",
      "Pengesahan lonjakan volume & momentum RSI melepasi paras pengesahan.",
      "Penguatkuasaan Nisbah Risk:Reward minimum 1:2.0 secara konsisten."
    ];
    const defaultRules = [
      "PERATURAN ADAPTIF #1: Wajibkan pengesahan Liquidity Sweep 15M sebelum pemicu entri SMC pada semua pasangan mata wang.",
      "PERATURAN ADAPTIF #2: Bekukan entri automatik 30 minit sebelum & selepas pengumuman berita berimpak tinggi.",
      "PERATURAN ADAPTIF #3: Besarkan penampan Stop Loss (SL Buffer) sebanyak 1.5x ATR pada zon volatiliti tinggi."
    ];
    const defaultTunings = [
      "Tingkatkan Stop Loss Buffer sebanyak 1.5x ATR untuk menyerap lonjakan spread (terutamanya XAU/USD).",
      "Kuatkuasakan saringan zon SMC pada timeframe M15/H1 sebelum eksekusi order pasaran.",
      "Kunci nisbah Risk:Reward minimum pada 1:2.0 bagi memastikan jangkaan keuntungan (positive expectancy)."
    ];
    const defaultExecutive = `Prestasi portfolio dinilai dari ${req.totalClosed} posisi sebenar PostgreSQL dengan kadar kemenangan ${req.winRate}% dan Net PnL $${req.netPnL}. Enjin telah menjana peraturan adaptif baharu bagi mengelakkan stop-hunt dan memaksimumkan keuntungan.`;

    if (!this.isAvailable()) {
      return {
        success: true,
        timestamp: Date.now(),
        tradesReviewedCount: req.totalClosed,
        winCount: req.winsCount,
        lossCount: req.lossesCount,
        winRate: req.winRate,
        netPnLDollars: req.netPnL,
        executiveSummaryMs: defaultExecutive,
        keyMistakesMs: defaultMistakes,
        winningPatternsMs: defaultWinning,
        generatedAdaptiveRulesMs: defaultRules,
        setupTuningRecommendationsMs: defaultTunings,
        primaryActiveRule: defaultRules[0],
        provider: 'local_fallback',
        tokensUsedEstimate: 0
      };
    }

    try {
      const compactPrompt = [
        `You are Senior Quantitative Desk Chief Risk Officer & Performance Mentor for Quantum AI.`,
        `Conduct a weekly continuous learning performance and setup tuning review for the algorithmic auto-trader:`,
        `Weekly Metrics:`,
        `- Closed Trades: ${req.totalClosed} (Wins: ${req.winsCount}, Losses: ${req.lossesCount})`,
        `- Win Rate: ${req.winRate}% | Net Realized PnL: $${req.netPnL}`,
        `- Sample Closed Trades: ${JSON.stringify((req.sampleClosedTrades || []).slice(0, 5))}`,
        `Tasks:`,
        `1. executiveSummaryMs: 1-2 sharp sentences in Bahasa Melayu on trading edge & vulnerabilities.`,
        `2. keyMistakesMs: Exactly 3 bullet points in Bahasa Melayu identifying root causes of losses.`,
        `3. winningPatternsMs: Exactly 3 bullet points in Bahasa Melayu identifying top winning confluences.`,
        `4. generatedAdaptiveRulesMs: Exactly 3 sharp, enforceable adaptive rules starting with "PERATURAN ADAPTIF #X:".`,
        `5. setupTuningRecommendationsMs: Exactly 3 actionable algorithmic parameter calibrations in Bahasa Melayu (e.g. SL ATR buffer, R:R minimum, Liquidity sweep timeframe, News freeze window).`,
        `6. primaryActiveRule: The single most critical adaptive rule string.`,
        `Respond strictly matching the JSON schema.`
      ].join('\n');

      const response = await this.client.integrations.Core.InvokeLLM({
        prompt: compactPrompt,
        response_json_schema: {
          type: 'object',
          properties: {
            executiveSummaryMs: { type: 'string' },
            keyMistakesMs: { type: 'array', items: { type: 'string' } },
            winningPatternsMs: { type: 'array', items: { type: 'string' } },
            generatedAdaptiveRulesMs: { type: 'array', items: { type: 'string' } },
            setupTuningRecommendationsMs: { type: 'array', items: { type: 'string' } },
            primaryActiveRule: { type: 'string' }
          },
          required: [
            'executiveSummaryMs',
            'keyMistakesMs',
            'winningPatternsMs',
            'generatedAdaptiveRulesMs',
            'setupTuningRecommendationsMs',
            'primaryActiveRule'
          ]
        }
      });

      console.log(`[Base44AiService] Completed Weekly Performance & Setup Tuning Review. Primary Rule: ${response.primaryActiveRule}`);

      return {
        success: true,
        timestamp: Date.now(),
        tradesReviewedCount: req.totalClosed,
        winCount: req.winsCount,
        lossCount: req.lossesCount,
        winRate: req.winRate,
        netPnLDollars: req.netPnL,
        executiveSummaryMs: response.executiveSummaryMs || defaultExecutive,
        keyMistakesMs: response.keyMistakesMs?.length ? response.keyMistakesMs : defaultMistakes,
        winningPatternsMs: response.winningPatternsMs?.length ? response.winningPatternsMs : defaultWinning,
        generatedAdaptiveRulesMs: response.generatedAdaptiveRulesMs?.length ? response.generatedAdaptiveRulesMs : defaultRules,
        setupTuningRecommendationsMs: response.setupTuningRecommendationsMs?.length ? response.setupTuningRecommendationsMs : defaultTunings,
        primaryActiveRule: response.primaryActiveRule || defaultRules[0],
        provider: 'base44',
        tokensUsedEstimate: 380
      };
    } catch (err: any) {
      console.warn(`[Base44AiService] Weekly Homework error: ${err.message}. Using deterministic fallback.`);
      return {
        success: true,
        timestamp: Date.now(),
        tradesReviewedCount: req.totalClosed,
        winCount: req.winsCount,
        lossCount: req.lossesCount,
        winRate: req.winRate,
        netPnLDollars: req.netPnL,
        executiveSummaryMs: defaultExecutive,
        keyMistakesMs: defaultMistakes,
        winningPatternsMs: defaultWinning,
        generatedAdaptiveRulesMs: defaultRules,
        setupTuningRecommendationsMs: defaultTunings,
        primaryActiveRule: defaultRules[0],
        provider: 'local_fallback',
        tokensUsedEstimate: 0
      };
    }
  }
}

export const base44AiService = Base44AiService.getInstance();
