import { pgTable, varchar, text, numeric, integer, boolean, timestamp, jsonb, bigint, index, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

// 0a. Multi-Tenant Tenants Table
export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), // 'ACTIVE' | 'SUSPENDED' | 'CANCELLED' | 'PENDING'
  tier: varchar('tier', { length: 32 }).notNull().default('PRO'),      // 'STARTER' | 'PRO' | 'ENTERPRISE'
  maxAccounts: integer('max_accounts').notNull().default(1),
  maxRiskCap: numeric('max_risk_cap', { precision: 5, scale: 2 }).notNull().default('2.00'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    emailIdx: index('idx_tenants_email').on(table.email),
    statusIdx: index('idx_tenants_status').on(table.status)
  };
});

// 0b. Subscriptions Table
export const subscriptions = pgTable('subscriptions', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  stripeCustomerId: varchar('stripe_customer_id', { length: 128 }).notNull(),
  stripeSubscriptionId: varchar('stripe_subscription_id', { length: 128 }).unique(),
  planId: varchar('plan_id', { length: 64 }).notNull(),
  status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), // 'ACTIVE' | 'TRIALING' | 'PAST_DUE' | 'CANCELLED' | 'UNPAID'
  currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }),
  cancelAtPeriodEnd: boolean('cancel_at_period_end').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tenantIdx: index('idx_subscriptions_tenant').on(table.tenantId),
    stripeCustIdx: index('idx_subscriptions_stripe_cust').on(table.stripeCustomerId),
    stripeSubIdx: index('idx_subscriptions_stripe_sub').on(table.stripeSubscriptionId)
  };
});

// 0c. Webhook Inbox Table (Idempotent Event Log)
export const webhookInbox = pgTable('webhook_inbox', {
  id: varchar('id', { length: 64 }).primaryKey(),
  eventId: varchar('event_id', { length: 128 }).notNull(),
  provider: varchar('provider', { length: 32 }).notNull().default('STRIPE'),
  eventType: varchar('event_type', { length: 128 }).notNull(),
  payload: jsonb('payload').notNull(),
  status: varchar('status', { length: 32 }).notNull().default('PENDING'), // 'PENDING' | 'PROCESSED' | 'FAILED' | 'DUPLICATE'
  processedAt: timestamp('processed_at', { withTimezone: true }),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    providerEventIdx: uniqueIndex('uq_webhook_inbox_provider_event').on(table.provider, table.eventId),
    statusIdx: index('idx_webhook_inbox_status').on(table.status),
    createdAtIdx: index('idx_webhook_inbox_created_at').on(table.createdAt)
  };
});

// 0d. Multi-Tenant Broker Connections Table (Secure Encrypted Credential Vault)
export const brokerConnections = pgTable('broker_connections', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  accountNumber: varchar('account_number', { length: 64 }).notNull(),
  brokerName: varchar('broker_name', { length: 64 }).notNull().default('CTRADER'),
  connectionType: varchar('connection_type', { length: 32 }).notNull().default('FIX_API'),
  encryptedCredentials: text('encrypted_credentials').notNull(),
  keyVersion: varchar('key_version', { length: 32 }).notNull().default('v1'),
  isActive: boolean('is_active').notNull().default(true),
  environment: varchar('environment', { length: 32 }).notNull().default('DEMO'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tenantIdx: index('idx_broker_connections_tenant').on(table.tenantId),
    accountIdx: index('idx_broker_connections_account').on(table.accountNumber)
  };
});

// 1. Signals Table (Canonical trading signals generated by AI/SMC engine)
export const signals = pgTable('signals', {
  id: varchar('id', { length: 64 }).primaryKey(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  timeframe: varchar('timeframe', { length: 16 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(), // 'BUY' | 'SELL'
  entryPrice: numeric('entry_price', { precision: 12, scale: 5 }).notNull(),
  stopLoss: numeric('stop_loss', { precision: 12, scale: 5 }).notNull(),
  takeProfit1: numeric('take_profit_1', { precision: 12, scale: 5 }).notNull(),
  takeProfit2: numeric('take_profit_2', { precision: 12, scale: 5 }).default('0'),
  setupType: varchar('setup_type', { length: 64 }),
  confidence: numeric('confidence', { precision: 5, scale: 2 }),
  reasoning: text('reasoning'),
  status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), // 'ACTIVE', 'EXECUTED', 'CANCELLED', 'EXPIRED', 'INVALIDATED'
  
  // Market Data Lineage & Provenance
  dataClass: varchar('data_class', { length: 32 }).notNull().default('UNKNOWN'), // 'LIVE', 'HISTORICAL', 'SIMULATION', 'SYNTHETIC'
  provider: varchar('provider', { length: 64 }).default('UNKNOWN'),
  source: varchar('source', { length: 64 }).default('UNKNOWN'),
  marketTimestamp: bigint('market_timestamp', { mode: 'number' }),
  executable: boolean('executable').default(true),
  strategy: varchar('strategy', { length: 64 }),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    symbolIdx: index('idx_signals_symbol').on(table.symbol),
    statusIdx: index('idx_signals_status').on(table.status),
    createdAtIdx: index('idx_signals_created_at').on(table.createdAt)
  };
});

// 2. Orders Table
export const orders = pgTable('orders', {
  orderId: varchar('order_id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  proposalId: varchar('proposal_id', { length: 64 }),
  approvalId: varchar('approval_id', { length: 64 }),
  accountId: varchar('account_id', { length: 64 }).notNull(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(), // 'BUY' | 'SELL'
  quantity: numeric('quantity', { precision: 12, scale: 4 }).notNull(),
  orderType: varchar('order_type', { length: 16 }).notNull().default('MARKET'),
  price: numeric('price', { precision: 12, scale: 5 }),
  stopLoss: numeric('stop_loss', { precision: 12, scale: 5 }),
  takeProfit: numeric('take_profit', { precision: 12, scale: 5 }),
  stopPrice: numeric('stop_price', { precision: 12, scale: 5 }),
  status: varchar('status', { length: 32 }).notNull(), // 'PENDING', 'SUBMITTED', 'FILLED', 'REJECTED', 'CANCELLED', 'EXPIRED'
  broker: varchar('broker', { length: 64 }).notNull().default('PAPER'),
  brokerOrderId: varchar('broker_order_id', { length: 128 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  filledAt: timestamp('filled_at', { withTimezone: true })
}, (table) => {
  return {
    tenantIdx: index('idx_orders_tenant').on(table.tenantId),
    accountIdx: index('idx_orders_account').on(table.accountId),
    statusIdx: index('idx_orders_status').on(table.status),
    symbolIdx: index('idx_orders_symbol').on(table.symbol)
  };
});

// 3. Order Fills / Executions Table
export const orderFills = pgTable('order_fills', {
  fillId: varchar('fill_id', { length: 64 }).primaryKey(),
  orderId: varchar('order_id', { length: 64 }).references(() => orders.orderId),
  filledPrice: numeric('filled_price', { precision: 12, scale: 5 }).notNull(),
  filledQuantity: numeric('filled_quantity', { precision: 12, scale: 4 }).notNull(),
  slippage: numeric('slippage', { precision: 8, scale: 5 }).notNull().default('0.00000'),
  latencyMs: integer('latency_ms').notNull().default(0),
  fee: numeric('fee', { precision: 8, scale: 2 }).notNull().default('0.00'),
  timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow()
});

// 4. Positions Table
export const positions = pgTable('positions', {
  positionId: varchar('position_id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  ticketId: varchar('ticket_id', { length: 128 }),
  setupId: varchar('setup_id', { length: 128 }),
  accountId: varchar('account_id', { length: 64 }).notNull(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  timeframe: varchar('timeframe', { length: 16 }).default('M15'),
  direction: varchar('direction', { length: 10 }).notNull(),
  quantity: numeric('quantity', { precision: 12, scale: 4 }).notNull(),
  entryPrice: numeric('entry_price', { precision: 12, scale: 5 }).notNull(),
  currentPrice: numeric('current_price', { precision: 12, scale: 5 }).notNull(),
  closePrice: numeric('close_price', { precision: 12, scale: 5 }),
  stopLoss: numeric('stop_loss', { precision: 12, scale: 5 }),
  takeProfit: numeric('take_profit', { precision: 12, scale: 5 }),
  takeProfit2: numeric('take_profit_2', { precision: 12, scale: 5 }),
  unrealizedProfit: numeric('unrealized_profit', { precision: 12, scale: 2 }).notNull().default('0.00'),
  realizedProfit: numeric('realized_profit', { precision: 12, scale: 2 }).notNull().default('0.00'),
  pnlPips: numeric('pnl_pips', { precision: 12, scale: 2 }).default('0.00'),
  commission: numeric('commission', { precision: 12, scale: 2 }).default('0.00'),
  swap: numeric('swap', { precision: 12, scale: 2 }).default('0.00'),
  status: varchar('status', { length: 16 }).notNull().default('OPEN'), // 'OPEN', 'CLOSED'
  closeReason: varchar('close_reason', { length: 64 }),
  broker: varchar('broker', { length: 64 }).default('PAPER'),
  environment: varchar('environment', { length: 32 }).default('DEMO'),
  proposalId: varchar('proposal_id', { length: 64 }),
  approvalId: varchar('approval_id', { length: 64 }),
  strategyId: varchar('strategy_id', { length: 64 }),
  strategyVersion: varchar('strategy_version', { length: 64 }),
  learningVersion: varchar('learning_version', { length: 32 }).default('1.0'),
  brokerOrderId: varchar('broker_order_id', { length: 64 }),
  brokerPositionId: varchar('broker_position_id', { length: 64 }),
  brokerDealId: varchar('broker_deal_id', { length: 64 }),
  reconciliationStatus: varchar('reconciliation_status', { length: 32 }).default('MATCHED'),
  idempotencyKey: varchar('idempotency_key', { length: 128 }),
  openedAt: timestamp('opened_at', { withTimezone: true }).defaultNow(),
  closedAt: timestamp('closed_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tenantIdx: index('idx_positions_tenant').on(table.tenantId),
    accountIdx: index('idx_positions_account').on(table.accountId),
    statusIdx: index('idx_positions_status').on(table.status),
    symbolIdx: index('idx_positions_symbol').on(table.symbol),
    idempotencyIdx: index('idx_positions_idempotency').on(table.idempotencyKey),
    reconciliationIdx: index('idx_positions_reconciliation').on(table.reconciliationStatus)
  };
});

// 4b. Trade Events Audit Table
export const tradeEvents = pgTable('trade_events', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tradeId: varchar('trade_id', { length: 128 }),
  orderId: varchar('order_id', { length: 128 }),
  setupId: varchar('setup_id', { length: 128 }),
  eventType: varchar('event_type', { length: 64 }).notNull(),
  actor: varchar('actor', { length: 64 }).default('SYSTEM'),
  details: jsonb('details'),
  timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tradeIdx: index('idx_trade_events_trade').on(table.tradeId),
    eventTypeIdx: index('idx_trade_events_type').on(table.eventType),
    timestampIdx: index('idx_trade_events_timestamp').on(table.timestamp)
  };
});

// 5. Execution Commands Table (from 003_execution_queue_and_lineage)
export const executionCommands = pgTable('execution_commands', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  setupId: varchar('setup_id', { length: 128 }).notNull(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  side: varchar('side', { length: 10 }).notNull(),
  volume: numeric('volume', { precision: 12, scale: 4 }).notNull(),
  entryPrice: numeric('entry_price', { precision: 12, scale: 5 }).notNull(),
  stopLoss: numeric('stop_loss', { precision: 12, scale: 5 }).notNull(),
  takeProfit1: numeric('take_profit_1', { precision: 12, scale: 5 }).notNull(),
  takeProfit2: numeric('take_profit_2', { precision: 12, scale: 5 }).default('0'),
  broker: varchar('broker', { length: 64 }).notNull().default('CTRADER'),
  accountNumber: varchar('account_number', { length: 64 }).notNull(),
  environment: varchar('environment', { length: 32 }).notNull().default('DEMO'),
  status: varchar('status', { length: 32 }).notNull().default('PENDING'),
  dataClass: varchar('data_class', { length: 32 }).notNull().default('UNKNOWN'),
  provider: varchar('provider', { length: 64 }).default('UNKNOWN'),
  timeframe: varchar('timeframe', { length: 16 }).default('M15'),
  idempotencyKey: varchar('idempotency_key', { length: 128 }).unique(),
  attemptCount: integer('attempt_count').default(0),
  lastAttemptAt: timestamp('last_attempt_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  executedAt: timestamp('executed_at', { withTimezone: true }),
  brokerOrderId: varchar('broker_order_id', { length: 128 }),
  claimedBy: varchar('claimed_by', { length: 64 }),
  leaseExpiry: timestamp('lease_expiry', { withTimezone: true }),
  error: text('error'),
  metadata: jsonb('metadata')
}, (table) => {
  return {
    tenantIdx: index('idx_execution_commands_tenant').on(table.tenantId),
    statusIdx: index('idx_execution_commands_status_v2').on(table.status),
    setupIdx: index('idx_execution_commands_setup_v2').on(table.setupId),
    accountIdx: index('idx_execution_commands_account_v2').on(table.accountNumber)
  };
});

// 6. Account State Table
export const accountState = pgTable('account_state', {
  accountId: varchar('account_id', { length: 64 }).primaryKey(),
  isAutoEnabled: boolean('is_auto_enabled').default(false),
  balance: numeric('balance', { precision: 12, scale: 2 }).notNull().default('10000.00'),
  initialCapital: numeric('initial_capital', { precision: 12, scale: 2 }).notNull().default('10000.00'),
  riskPercent: numeric('risk_percent', { precision: 5, scale: 2 }).notNull().default('1.00'),
  latestAiRule: text('latest_ai_rule'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
});

// 7. Trading Audit Logs Table
export const tradingLogs = pgTable('trading_logs', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  accountId: varchar('account_id', { length: 64 }).notNull().default('DEFAULT'),
  timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow(),
  text: text('text').notNull(),
  type: varchar('type', { length: 32 }).notNull().default('INFO')
}, (table) => {
  return {
    tenantIdx: index('idx_trading_logs_tenant').on(table.tenantId)
  };
});

// 8. Journal Entries Table
export const journalEntries = pgTable('journal_entries', {
  id: varchar('id', { length: 64 }).primaryKey(),
  accountId: varchar('account_id', { length: 64 }).default('DEFAULT'),
  pair: varchar('pair', { length: 32 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(),
  entryPrice: numeric('entry_price', { precision: 12, scale: 5 }).notNull(),
  exitPrice: numeric('exit_price', { precision: 12, scale: 5 }),
  resultPnl: numeric('result_pnl', { precision: 12, scale: 2 }).notNull().default('0.00'),
  tags: jsonb('tags'),
  notes: text('notes'),
  timestamp: bigint('timestamp', { mode: 'number' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow()
});

// 9. Post Mortem Reviews Table
export const postMortemReviews = pgTable('post_mortem_reviews', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tradeId: varchar('trade_id', { length: 64 }).notNull(),
  learningVersion: varchar('learning_version', { length: 32 }).notNull().default('1.0'),
  review: jsonb('review').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tradeLearningIdx: uniqueIndex('idx_post_mortem_trade_version').on(table.tradeId, table.learningVersion)
  };
});

// 10. Broker Webhook Inbox Table (Phase 5G Webhook Inbox)
export const brokerWebhookEvents = pgTable('broker_webhook_events', {
  eventId: varchar('event_id', { length: 128 }).primaryKey(),
  broker: varchar('broker', { length: 64 }).notNull(),
  eventType: varchar('event_type', { length: 64 }).notNull(),
  accountNumber: varchar('account_number', { length: 64 }),
  orderId: varchar('order_id', { length: 128 }),
  payload: jsonb('payload').notNull(),
  status: varchar('status', { length: 32 }).notNull().default('RECEIVED'), // 'RECEIVED', 'PROCESSED', 'FAILED'
  error: text('error'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  processedAt: timestamp('processed_at', { withTimezone: true })
}, (table) => {
  return {
    statusIdx: index('idx_broker_webhook_status').on(table.status),
    orderIdx: index('idx_broker_webhook_order').on(table.orderId)
  };
});

// 11. Outbox Events Table (Phase 5G Event Consistency)
export const outboxEvents = pgTable('outbox_events', {
  id: varchar('id', { length: 64 }).primaryKey(),
  eventType: varchar('event_type', { length: 64 }).notNull(),
  payload: jsonb('payload').notNull(),
  status: varchar('status', { length: 32 }).notNull().default('PENDING'), // 'PENDING', 'PUBLISHED', 'FAILED'
  retryCount: integer('retry_count').default(0),
  error: text('error'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  publishedAt: timestamp('published_at', { withTimezone: true })
}, (table) => {
  return {
    statusIdx: index('idx_outbox_events_status').on(table.status),
    createdAtIdx: index('idx_outbox_events_created_at').on(table.createdAt)
  };
});

// 12. Execution Audit Trail Table (Phase 5G Append-Only Audit)
export const executionAuditLogs = pgTable('execution_audit_logs', {
  id: varchar('id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  commandId: varchar('command_id', { length: 64 }).notNull(),
  setupId: varchar('setup_id', { length: 128 }),
  fromStatus: varchar('from_status', { length: 32 }),
  toStatus: varchar('to_status', { length: 32 }).notNull(),
  actor: varchar('actor', { length: 64 }).notNull(),
  details: jsonb('details'),
  timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tenantIdx: index('idx_execution_audit_logs_tenant').on(table.tenantId),
    commandIdx: index('idx_exec_audit_command').on(table.commandId),
    timestampIdx: index('idx_exec_audit_timestamp').on(table.timestamp)
  };
});

// 13. Reconciliation Records Table (Phase 5G Reconciliation Durability)
export const reconciliationRecords = pgTable('reconciliation_records', {
  id: varchar('id', { length: 64 }).primaryKey(),
  accountId: varchar('account_id', { length: 64 }).notNull().default('DEFAULT'),
  broker: varchar('broker', { length: 64 }).notNull(),
  action: varchar('action', { length: 64 }).notNull(),
  targetId: varchar('target_id', { length: 128 }).notNull(),
  details: jsonb('details'),
  timestamp: timestamp('timestamp', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    targetIdx: index('idx_reconciliation_target').on(table.targetId),
    timestampIdx: index('idx_reconciliation_timestamp').on(table.timestamp)
  };
});

// 14. Durable Idempotency Storage Table
export const idempotencyRecords = pgTable('idempotency_records', {
  key: varchar('key', { length: 128 }).primaryKey(),
  scope: varchar('scope', { length: 64 }).notNull(),
  result: jsonb('result').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow()
});

// 15. Manual Trades Table (Phase 6E: Durable Manual Trading Ledger)
export const manualTrades = pgTable('manual_trades', {
  manualTradeId: varchar('manual_trade_id', { length: 64 }).primaryKey(),
  tenantId: uuid('tenant_id').notNull().default('00000000-0000-0000-0000-000000000000'),
  signalId: varchar('signal_id', { length: 64 }).notNull(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(),
  actualEntry: numeric('actual_entry', { precision: 12, scale: 5 }).notNull(),
  positionSize: numeric('position_size', { precision: 8, scale: 4 }).notNull(),
  enteredAt: timestamp('entered_at', { withTimezone: true }).notNull().defaultNow(),
  status: varchar('status', { length: 16 }).notNull().default('ACTIVE'),
  exitPrice: numeric('exit_price', { precision: 12, scale: 5 }),
  exitReason: varchar('exit_reason', { length: 64 }),
  exitedAt: timestamp('exited_at', { withTimezone: true }),
  realizedPnl: numeric('realized_pnl', { precision: 12, scale: 2 }),
  realizedPips: numeric('realized_pips', { precision: 10, scale: 2 }),
  result: varchar('result', { length: 16 }),
  executionMode: varchar('execution_mode', { length: 32 }).notNull().default('MANUAL'),
  brokerExecution: boolean('broker_execution').notNull().default(false),
  source: varchar('source', { length: 64 }).notNull().default('MANUAL_USER_REPORTED'),
  notes: text('notes'),
  aiPlannedSetup: jsonb('ai_planned_setup').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tenantIdx: index('idx_manual_trades_tenant').on(table.tenantId),
    statusIdx: index('idx_manual_trades_status').on(table.status),
    signalIdx: index('idx_manual_trades_signal').on(table.signalId),
    symbolIdx: index('idx_manual_trades_symbol').on(table.symbol),
    createdIdx: index('idx_manual_trades_created').on(table.createdAt)
  };
});

// 16. Manual Trade Alerts Table (Phase 6E: Deduplicated Monitoring Alerts)
export const manualTradeAlerts = pgTable('manual_trade_alerts', {
  alertId: varchar('alert_id', { length: 128 }).primaryKey(),
  manualTradeId: varchar('manual_trade_id', { length: 64 }).notNull(),
  signalId: varchar('signal_id', { length: 64 }).notNull(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(),
  triggerType: varchar('trigger_type', { length: 64 }).notNull(),
  triggeredAt: timestamp('triggered_at', { withTimezone: true }).notNull().defaultNow(),
  triggerPrice: numeric('trigger_price', { precision: 12, scale: 5 }).notNull(),
  thresholdPrice: numeric('threshold_price', { precision: 12, scale: 5 }).notNull(),
  unrealizedPips: numeric('unrealized_pips', { precision: 10, scale: 2 }).notNull(),
  unrealizedPnl: numeric('unrealized_pnl', { precision: 12, scale: 2 }).notNull(),
  message: text('message').notNull(),
  acknowledged: boolean('acknowledged').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    tradeIdx: index('idx_manual_trade_alerts_trade').on(table.manualTradeId),
    triggerIdx: index('idx_manual_trade_alerts_trigger').on(table.triggerType),
    createdIdx: index('idx_manual_trade_alerts_created').on(table.createdAt)
  };
});

// 17. Shadow Observations Table (Durable Shadow Forward-Testing Isolation)
export const shadowObservations = pgTable('shadow_observations', {
  id: varchar('id', { length: 64 }).primaryKey(),
  signalId: varchar('signal_id', { length: 64 }).notNull(),
  symbol: varchar('symbol', { length: 32 }).notNull(),
  direction: varchar('direction', { length: 10 }).notNull(),
  setupType: varchar('setup_type', { length: 64 }).notNull(),
  setupFingerprint: varchar('setup_fingerprint', { length: 128 }).notNull(),
  session: varchar('session', { length: 32 }).notNull(),
  marketRegime: varchar('market_regime', { length: 64 }).notNull(),

  // Price parameters
  entryPrice: numeric('entry_price', { precision: 12, scale: 5 }).notNull(),
  stopLoss: numeric('stop_loss', { precision: 12, scale: 5 }).notNull(),
  initialStopLoss: numeric('initial_stop_loss', { precision: 12, scale: 5 }).notNull(),
  takeProfit1: numeric('take_profit_1', { precision: 12, scale: 5 }).notNull(),
  takeProfit2: numeric('take_profit_2', { precision: 12, scale: 5 }),
  isMultiTarget: boolean('is_multi_target').notNull().default(false),
  tp1Hit: boolean('tp1_hit').notNull().default(false),

  // Exit & Outcome
  status: varchar('status', { length: 16 }).notNull().default('ACTIVE'),
  closeReason: varchar('close_reason', { length: 64 }),
  exitPrice: numeric('exit_price', { precision: 12, scale: 5 }),
  realizedR: numeric('realized_r', { precision: 8, scale: 2 }),

  // High-water mark excursions
  mfePips: numeric('mfe_pips', { precision: 8, scale: 1 }).notNull().default('0.0'),
  maePips: numeric('mae_pips', { precision: 8, scale: 1 }).notNull().default('0.0'),
  highestPriceSeen: numeric('highest_price_seen', { precision: 12, scale: 5 }).notNull(),
  lowestPriceSeen: numeric('lowest_price_seen', { precision: 12, scale: 5 }).notNull(),

  // Observational metadata & Immutable Snapshot
  monitoringState: varchar('monitoring_state', { length: 32 }).notNull().default('LIVE_MONITORING'),
  observationType: varchar('observation_type', { length: 32 }).notNull().default('SHADOW_OBSERVATION'),
  executionQualityAssumptions: jsonb('execution_quality_assumptions').notNull(),
  immutableSignalSnapshot: jsonb('immutable_signal_snapshot').notNull(),

  // Timestamps
  openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
  closedAt: timestamp('closed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    symbolIdx: index('idx_shadow_obs_symbol').on(table.symbol),
    statusIdx: index('idx_shadow_obs_status').on(table.status),
    signalIdx: index('idx_shadow_obs_signal').on(table.signalId),
    openedAtIdx: index('idx_shadow_obs_opened_at').on(table.openedAt),
    closedAtIdx: index('idx_shadow_obs_closed_at').on(table.closedAt),
    fingerprintIdx: index('idx_shadow_obs_fingerprint').on(table.setupFingerprint)
  };
});

// 18. Learning Journal Events Table (Durable Event Ledger)
export const learningJournalEvents = pgTable('learning_journal_events', {
  id: varchar('id', { length: 64 }).primaryKey(),
  eventType: varchar('event_type', { length: 64 }).notNull(),
  setupFingerprint: varchar('setup_fingerprint', { length: 128 }),
  symbol: varchar('symbol', { length: 32 }),
  direction: varchar('direction', { length: 10 }),
  session: varchar('session', { length: 32 }),
  observationType: varchar('observation_type', { length: 32 }),
  observationId: varchar('observation_id', { length: 64 }),
  tradeId: varchar('trade_id', { length: 64 }),
  outcome: varchar('outcome', { length: 16 }),
  realizedR: numeric('realized_r', { precision: 8, scale: 2 }),
  mfePips: numeric('mfe_pips', { precision: 8, scale: 1 }),
  maePips: numeric('mae_pips', { precision: 8, scale: 1 }),
  sampleCount: integer('sample_count').notNull().default(0),
  evidenceTier: varchar('evidence_tier', { length: 32 }),
  previousLearningWeight: numeric('previous_learning_weight', { precision: 6, scale: 4 }),
  newLearningWeight: numeric('new_learning_weight', { precision: 6, scale: 4 }),
  previousParameter: text('previous_parameter'),
  proposedParameter: text('proposed_parameter'),
  appliedParameter: text('applied_parameter'),
  boundedAdjustment: text('bounded_adjustment'),
  reason: text('reason').notNull(),
  confidenceBasis: text('confidence_basis'),
  affectedFutureSetupFingerprint: varchar('affected_future_setup_fingerprint', { length: 128 }),
  payload: jsonb('payload'),
  timestamp: bigint('timestamp', { mode: 'number' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow()
}, (table) => {
  return {
    fingerprintIdx: index('idx_lje_fingerprint').on(table.setupFingerprint),
    typeIdx: index('idx_lje_type').on(table.eventType),
    timestampIdx: index('idx_lje_timestamp').on(table.timestamp)
  };
});
